import React from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Links } from '@/components/Links'
import { Headline } from '@/components/Headline'
import { Footer } from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <React.Fragment>
      <Head>
        <title>About pages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <Headline page="about" />

        <Links />
      </main>

      <Footer />
    </React.Fragment>
  )
}
